/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.1.4 public/models/recumbent_lion.glb --transform
Author: Geoffrey Marchal (https://sketchfab.com/geoffreymarchal)
License: CC-BY-NC-4.0 (http://creativecommons.org/licenses/by-nc/4.0/)
Source: https://sketchfab.com/3d-models/recumbent-lion-455b37b9e58d43dba5b6c0ab269e242a
Title: Recumbent lion
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/recumbent_lion-transformed.glb')
  return (
    <group {...props} dispose={null}>
      <group position={[9495.37, -14235.19, -42344.94]} rotation={[-3.12, 0.31, 0.03]}>
        <group position={[-28927.67, 5322.56, -43764.48]}>
          <mesh geometry={nodes.Object_2.geometry} material={materials.Material_0} />
          <mesh geometry={nodes.Object_3.geometry} material={materials.Material_0} />
          <mesh geometry={nodes.Object_4.geometry} material={materials.Material_0} />
          <mesh geometry={nodes.Object_5.geometry} material={materials.Material_0} />
        </group>
      </group>
    </group>
  )
}

useGLTF.preload('/recumbent_lion-transformed.glb')
